version: "3.5"
services:

    otrs-db:
        image: postgres:10.3-alpine
        volumes:
            - otrs-db:/var/lib/postgresql/data
        networks:
            - otrs-backend
        environment:
            POSTGRES_PASSWORD_FILE: dbpassword.txt
        restart: unless-stopped

    otrs-fcgi:
        image: snw35/otrs-fcgi:latest
        volumes:
            - type: volume
              source: otrs-config
              target: /data
            - type: volume
              source: otrs-dir
              target: /opt/otrs
            - type: tmpfs
              target: /tmp
        ports:
            - 9000
        networks:
            - otrs-backend
        depends_on:
            - otrs-db
        restart: unless-stopped

    otrs-nginx:
        image: snw35/otrs-nginx:latest
        volumes:
            - otrs-config:/data
            - otrs-dir:/opt/otrs
        ports:
            - 80:80
        networks:
            - otrs-backend
        depends_on:
            - otrs-fcgi
        restart: unless-stopped

    otrs-daemon:
        image: snw35/otrs-daemon:latest
        volumes:
            - otrs-config:/data
            - otrs-dir:/opt/otrs
        networks:
            - otrs-backend
        depends_on:
            - otrs-db
            - otrs-fcgi
        restart: unless-stopped

volumes:
    otrs-db:
        external:
            name: otrs-db
    otrs-config:
        external:
            name: otrs-config
    otrs-dir:

networks:
    otrs-backend:
